# Generated by Django 6.0.6 on 2026-06-11 11:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('numero_affiliation', models.CharField(max_length=7, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[1-9][0-9]{6}$', 'Le numéro doit contenir 7 chiffres et ne pas commencer par 0')])),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('classement', models.CharField(choices=[('A', 'A'), ('B-15.4', 'B-15.4'), ('B-15.2', 'B-15.2'), ('B-15.1', 'B-15.1'), ('B15', 'B15'), ('B-4/6', 'B-4/6'), ('B-2/6', 'B-2/6'), ('B0', 'B0'), ('B+2/6', 'B+2/6'), ('B+4/6', 'B+4/6'), ('C15', 'C15'), ('C15.1', 'C15.1'), ('C15.2', 'C15.2'), ('C15.3', 'C15.3'), ('C15.4', 'C15.4'), ('C30', 'C30'), ('C30.1', 'C30.1'), ('C30.2', 'C30.2'), ('C30.3', 'C30.3'), ('C30.4', 'C30.4'), ('C30.5', 'C30.5'), ('N.C', 'N.C')], max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=False)),
                ('premiere_connexion', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('membre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tennis.membre')),
            ],
            options={
                'verbose_name': 'Administrateur',
            },
            bases=('tennis.membre',),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('type_jeu', models.CharField(choices=[('simple', 'Simple'), ('double', 'Double')], max_length=10)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tennis.membre')),
                ('partenaire1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_partenaire1', to='tennis.membre')),
                ('partenaire2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_partenaire2', to='tennis.membre')),
                ('partenaire3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_partenaire3', to='tennis.membre')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.terrain')),
            ],
        ),
        migrations.CreateModel(
            name='BlocageTerrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('motif', models.CharField(max_length=100)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.terrain')),
            ],
        ),
    ]
